// Mocks generated by Mockito 5.4.5 from annotations
// in building_manage_front/test/modules/manager/attendance_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:building_manage_front/modules/manager/data/datasources/attendance_remote_datasource.dart'
    as _i6;
import 'package:building_manage_front/modules/manager/domain/entities/attendance_record.dart'
    as _i2;
import 'package:building_manage_front/modules/manager/domain/usecases/check_in_usecase.dart'
    as _i3;
import 'package:building_manage_front/modules/manager/domain/usecases/check_out_usecase.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMonthlyAttendanceResponse_0 extends _i1.SmartFake
    implements _i2.MonthlyAttendanceResponse {
  _FakeMonthlyAttendanceResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CheckInUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckInUseCase extends _i1.Mock implements _i3.CheckInUseCase {
  MockCheckInUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, dynamic>> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [CheckOutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckOutUseCase extends _i1.Mock implements _i5.CheckOutUseCase {
  MockCheckOutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, dynamic>> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [AttendanceRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAttendanceRemoteDataSource extends _i1.Mock
    implements _i6.AttendanceRemoteDataSource {
  MockAttendanceRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, dynamic>> checkIn() => (super.noSuchMethod(
        Invocation.method(
          #checkIn,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> checkOut() => (super.noSuchMethod(
        Invocation.method(
          #checkOut,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<String> getTodayAttendanceStatus() => (super.noSuchMethod(
        Invocation.method(
          #getTodayAttendanceStatus,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getTodayAttendanceStatus,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i2.MonthlyAttendanceResponse> getMonthlyAttendance({
    required int? year,
    required int? month,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthlyAttendance,
          [],
          {
            #year: year,
            #month: month,
          },
        ),
        returnValue: _i4.Future<_i2.MonthlyAttendanceResponse>.value(
            _FakeMonthlyAttendanceResponse_0(
          this,
          Invocation.method(
            #getMonthlyAttendance,
            [],
            {
              #year: year,
              #month: month,
            },
          ),
        )),
      ) as _i4.Future<_i2.MonthlyAttendanceResponse>);
}
