// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4LbyazXPotuUPrlaRPdCIfuMzLTHJl0o',
    appId: '1:1010780994133:web:7fbbb905204a03d70632dc',
    messagingSenderId: '1010780994133',
    projectId: 'building-management-935a4',
    authDomain: 'building-management-935a4.firebaseapp.com',
    storageBucket: 'building-management-935a4.firebasestorage.app',
    measurementId: 'G-PEXKLC6RTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEN-wplH6PW_zZ6igcuCxzZkfFaAuCD9E',
    appId: '1:1010780994133:android:6a33be673a06945f0632dc',
    messagingSenderId: '1010780994133',
    projectId: 'building-management-935a4',
    storageBucket: 'building-management-935a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACuFkJlAClaVAwjwZk3Hq380YxU9WINjg',
    appId: '1:1010780994133:ios:836bf5137e11399d0632dc',
    messagingSenderId: '1010780994133',
    projectId: 'building-management-935a4',
    storageBucket: 'building-management-935a4.firebasestorage.app',
    iosBundleId: 'com.example.buildingManageFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACuFkJlAClaVAwjwZk3Hq380YxU9WINjg',
    appId: '1:1010780994133:ios:836bf5137e11399d0632dc',
    messagingSenderId: '1010780994133',
    projectId: 'building-management-935a4',
    storageBucket: 'building-management-935a4.firebasestorage.app',
    iosBundleId: 'com.example.buildingManageFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4LbyazXPotuUPrlaRPdCIfuMzLTHJl0o',
    appId: '1:1010780994133:web:901d5c07e78def690632dc',
    messagingSenderId: '1010780994133',
    projectId: 'building-management-935a4',
    authDomain: 'building-management-935a4.firebaseapp.com',
    storageBucket: 'building-management-935a4.firebasestorage.app',
    measurementId: 'G-M2NJ7VEMJW',
  );
}